[package]
name = "ex25"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "p1"
path = "src/p1.rs"

[dependencies]
itertools = "0.12.0"
rand = "0.8.5"
